version: '2'
services:
  basicserver:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
  jaeger:
    image: jaegertracing/all-in-one:1.31
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - JAEGER_AGENT_PORT=6831
      - JAEGER_AGENT_HOST=jaeger
      - SAMPLING_CONFIG_TYPE=adaptive
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "8090:80/udp"
      - "8090:80/tcp"

